FROM ubuntu:latest

# 安装必要工具和依赖
RUN apt-get update && apt-get install -y curl

# 安装Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs

# 安装Python、Java、Golang、C/C++编译器
RUN apt-get install -y \
    python3 \
    openjdk-17-jdk \
    golang \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /code
